# Imports

In [34]:
import pandas as pd
import numpy as np

import joblib

import sys, os
from pathlib import Path

# adiciona a pasta src ao path
sys.path.append(os.path.abspath("../src"))

# importa tudo do funcs.py
from funcs import trata_df_final, trata_colunas_categoricas

In [35]:
# carregando df
df = pd.read_csv('../dados/dataset_final/clientes_clusterizados.csv', sep=';')

In [36]:
# carregando modelo
modelo_kproto = joblib.load("modelo_kproto.joblib")

In [37]:
df

,CD_CLIENTE,DS_PROD_MODA,DS_LIN_REC_MODA,CIDADE,DS_CNAE,DS_SEGMENTO,DS_SUBSEGMENTO,MARCA_TOTVS_MODA,MODAL_COMERC_MODA,PAIS,...,UF,VL_TOTAL_CONTRATO_SOMA,FAIXA_VLR_TOT_SOMA_CONTRATOS,DIAS_CLIENTE,QTD_CONTRATACOES_12M,VLR_CONTRATACOES_12M,CLUSTER_3,CLUSTER_4,CLUSTER_5,CLUSTER_6
0,99069,CLOUD IAAS 36M,SAAS SERIE T,SAOPAULO,COMERCIO VAREJISTA ESPECIALIZADO DE EQUIPAMENT...,VAREJO,VAREJO,CLOUD,MODALIDADE ASSINATURA COMPLEMENTAR,105,...,SP,8.120772e+03,0.0-0.5M,2943,0.0,0.000000,0,2,3,2
1,99958,ADESAO TOTVS P,SAAS SMS ALUGUEL,JOINVILLE,PESSOA FISICA (SEM CNAE),SERVICOS,PROVEDOR SERVICOS,CROSS - TRADICIONAL,MODALIDADE ALUGUEL (LEGADO),105,...,SC,1.634142e+06,1.5-2.0M,3454,0.0,0.000000,0,1,4,1
2,99999,CR.WN06.CsA,CDU TOTVS SERIE T,SAOPAULO,Desenvolvimento de programas de computador sob...,TOTVS,TOTVS,MODALIDADE TRADICIONAL,MODALIDADE TRADICIONAL,105,...,SP,4.271960e+01,0.0-0.5M,7037,0.0,0.000000,0,2,3,2
3,CARAMU,ADESAO OT LOG PLA 500 VIAGENS,CDU TOTVS SERIE T,ITUMBIARA,"Fabricacao de oleos vegetais refinados, exceto...",MANUFATURA,BENS DE CONSUMO,OTIMIZACAO LOGISTICA,MODALIDADE ASSINATURA COMPLEMENTAR,105,...,GO,8.531457e+04,0.0-0.5M,1192,0.0,0.000000,0,2,3,2
4,T00018,CDU LGT G CAP HUMANO TRAD,CDU TOTVS SERIE T,SAOPAULO,Hoteis,SERVICOS,VIAGENS,HOSPITALIDADE - CORE,MODALIDADE TRADICIONAL,105,...,SP,2.051230e+02,0.0-0.5M,8664,0.0,0.000000,0,2,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10610,TFEEXW,05 IDS FLUIG PLATAFORMA,SAAS INTERA SOFTWARE,BELOHORIZONTE,"Atividades de atendimento hospitalar, exceto p...",SAUDE,HOSPITAIS,RH - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,...,MG,3.041294e+04,0.0-0.5M,184,2.0,30412.949059,0,2,3,2
10611,TFEEYC,TEF TOTVS CLOUD PDV PRINCIPAL,SAAS TEF,GOIANIA,Comercio varejista de calcados,VAREJO,MODA,DISTRIBUICAO & VAREJO - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,...,GO,6.010675e+01,0.0-0.5M,181,1.0,60.106753,0,2,3,2
10612,TFEEYH,CONS SAT OU MFE BALANC SUBSC,SAAS SERIE T,ITAITINGA,"Comercio varejista de mercadorias em geral, co...",VAREJO,SUPERMERCADO,SUPERMERCADOS - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,...,CE,3.600225e+02,0.0-0.5M,181,1.0,360.022549,0,2,3,2
10613,TFEEYP,ALMOXARIFADO E ESTOQUE,SAAS CMNET HOTAL,CANELA,Hoteis,HOSPITALITY,HOSPEDAGEM,HOSPITALIDADE - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,...,RS,1.705934e+03,0.0-0.5M,181,1.0,1705.933728,0,2,3,2
10614,TFEEYQ,ADESAO TOTVS P,CLOUD COMPUTING.,SAOPAULO,Servicos advocaticios,JURIDICO,ESCRITORIO DE ADVOCACIA,CLOUD,MODALIDADE SERVICOS RECORRENTES,105,...,SP,5.656080e+03,0.0-0.5M,181,1.0,5656.079896,0,2,3,2

In [38]:
# criando copia
df_copy = df.copy(deep=True)

# Funções

In [39]:
# função p criação e clusterização de novo cliente

def clusterizar_novo_cliente(cluster, df_original, modelo_kproto, restrito=True):

    # opção para usar apenas um cluster como base
    if restrito:
        # Define cluster aleatório entre 0 e 5
        df_original = df_original[df_original['CLUSTER_5'] == cluster]

    # cliente sample
    df_original = df_original.sample(n=1, random_state=42)

    # removendo colunas de clusterização
    df_original.drop(columns=['CLUSTER_3', 'CLUSTER_4', 'CLUSTER_5', 'CLUSTER_6'], inplace=True)

    print(df_original)

    # tratamento valores
    df3, df4, df_novo_cliente_1 = trata_df_final(df_original, normalizar = False)

    print(df_novo_cliente_1)

    # Separando colunas categoricas
    categorical_idx = trata_colunas_categoricas(df_novo_cliente_1)

    # definindo cluster
    cluster_previsto = modelo_kproto.predict(
        X=df_novo_cliente_1,
        categorical=categorical_idx
    )

    print(cluster_previsto)

    cluster_resultado = cluster_previsto[0]

    return cluster_resultado, df_novo_cliente_1

# Clusterização do novo cliente

In [40]:
########################## RODAR A PARTIR DAQUI PARA BAIXO PARA NOVO CLIENTE ######################################

In [41]:
numero_aleatorio = np.random.randint(0, 5)

In [42]:
numero_aleatorio

3

In [43]:
# Gernarando e clusterizando novo cliente
# Escolha 'True' para usar apenas um cluster como base

cluster_resultado, df_novo_cliente_1 = clusterizar_novo_cliente(numero_aleatorio, df_copy, modelo_kproto, True)

     CD_CLIENTE               DS_PROD_MODA   DS_LIN_REC_MODA    CIDADE  \
2186     TA2584  APLICATIVO MOBILE - STAFF  SAAS CMNET HOTAL  SAOPAULO

           DS_CNAE  DS_SEGMENTO DS_SUBSEGMENTO      MARCA_TOTVS_MODA  \
2186  Apart-hoteis  HOSPITALITY     HOSPEDAGEM  HOSPITALIDADE - CORE

                       MODAL_COMERC_MODA  PAIS PERIODICIDADE_MODA  UF  \
2186  MODALIDADE ASSINATURA COMPLEMENTAR   105        00 - Mensal  SP

      VL_TOTAL_CONTRATO_SOMA FAIXA_VLR_TOT_SOMA_CONTRATOS  DIAS_CLIENTE  \
2186              401.569271                     0.0-0.5M          2887

      QTD_CONTRATACOES_12M  VLR_CONTRATACOES_12M
2186                   0.0                   0.0
      CD_CLIENTE               DS_PROD_MODA   DS_LIN_REC_MODA    CIDADE  \
2186           0  APLICATIVO MOBILE - STAFF  SAAS CMNET HOTAL  SAOPAULO

           DS_CNAE  DS_SEGMENTO DS_SUBSEGMENTO      MARCA_TOTVS_MODA  \
2186  Apart-hoteis  HOSPITALITY     HOSPEDAGEM  HOSPITALIDADE - CORE

                       MODAL_COMERC_MODA  PAIS PERIODICIDADE_MODA  UF  \
2186  MODALIDADE ASSINATURA COMPLEMENTAR   105        00 - Mensal  SP

      VL_TOTAL_CONTRATO_SOMA FAIXA_VLR_TOT_SOMA_CONTRATOS  DIAS_CLIENTE  \
2186              401.569271                     0.0-0.5M          2887

      QTD_CONTRATACOES_12M  VLR_CONTRATACOES_12M
2186                   0.0                   0.0
[3]

In [44]:
cluster_resultado

np.uint16(3)

In [45]:
df_novo_cliente_1.T

                                                            2186
CD_CLIENTE                                                     0
DS_PROD_MODA                           APLICATIVO MOBILE - STAFF
DS_LIN_REC_MODA                                 SAAS CMNET HOTAL
CIDADE                                                  SAOPAULO
DS_CNAE                                             Apart-hoteis
DS_SEGMENTO                                          HOSPITALITY
DS_SUBSEGMENTO                                        HOSPEDAGEM
MARCA_TOTVS_MODA                            HOSPITALIDADE - CORE
MODAL_COMERC_MODA             MODALIDADE ASSINATURA COMPLEMENTAR
PAIS                                                         105
PERIODICIDADE_MODA                                   00 - Mensal
UF                                                            SP
VL_TOTAL_CONTRATO_SOMA                                401.569271
FAIXA_VLR_TOT_SOMA_CONTRATOS                            0.0-0.5M
DIAS_CLIENTE                                                2887
QTD_CONTRATACOES_12M                                         0.0
VLR_CONTRATACOES_12M                                         0.0

# Vsualização do cliente no plano

## Concatenando

In [46]:
df

,CD_CLIENTE,DS_PROD_MODA,DS_LIN_REC_MODA,CIDADE,DS_CNAE,DS_SEGMENTO,DS_SUBSEGMENTO,MARCA_TOTVS_MODA,MODAL_COMERC_MODA,PAIS,...,UF,VL_TOTAL_CONTRATO_SOMA,FAIXA_VLR_TOT_SOMA_CONTRATOS,DIAS_CLIENTE,QTD_CONTRATACOES_12M,VLR_CONTRATACOES_12M,CLUSTER_3,CLUSTER_4,CLUSTER_5,CLUSTER_6
0,99069,CLOUD IAAS 36M,SAAS SERIE T,SAOPAULO,COMERCIO VAREJISTA ESPECIALIZADO DE EQUIPAMENT...,VAREJO,VAREJO,CLOUD,MODALIDADE ASSINATURA COMPLEMENTAR,105,...,SP,8.120772e+03,0.0-0.5M,2943,0.0,0.000000,0,2,3,2
1,99958,ADESAO TOTVS P,SAAS SMS ALUGUEL,JOINVILLE,PESSOA FISICA (SEM CNAE),SERVICOS,PROVEDOR SERVICOS,CROSS - TRADICIONAL,MODALIDADE ALUGUEL (LEGADO),105,...,SC,1.634142e+06,1.5-2.0M,3454,0.0,0.000000,0,1,4,1
2,99999,CR.WN06.CsA,CDU TOTVS SERIE T,SAOPAULO,Desenvolvimento de programas de computador sob...,TOTVS,TOTVS,MODALIDADE TRADICIONAL,MODALIDADE TRADICIONAL,105,...,SP,4.271960e+01,0.0-0.5M,7037,0.0,0.000000,0,2,3,2
3,CARAMU,ADESAO OT LOG PLA 500 VIAGENS,CDU TOTVS SERIE T,ITUMBIARA,"Fabricacao de oleos vegetais refinados, exceto...",MANUFATURA,BENS DE CONSUMO,OTIMIZACAO LOGISTICA,MODALIDADE ASSINATURA COMPLEMENTAR,105,...,GO,8.531457e+04,0.0-0.5M,1192,0.0,0.000000,0,2,3,2
4,T00018,CDU LGT G CAP HUMANO TRAD,CDU TOTVS SERIE T,SAOPAULO,Hoteis,SERVICOS,VIAGENS,HOSPITALIDADE - CORE,MODALIDADE TRADICIONAL,105,...,SP,2.051230e+02,0.0-0.5M,8664,0.0,0.000000,0,2,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10610,TFEEXW,05 IDS FLUIG PLATAFORMA,SAAS INTERA SOFTWARE,BELOHORIZONTE,"Atividades de atendimento hospitalar, exceto p...",SAUDE,HOSPITAIS,RH - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,...,MG,3.041294e+04,0.0-0.5M,184,2.0,30412.949059,0,2,3,2
10611,TFEEYC,TEF TOTVS CLOUD PDV PRINCIPAL,SAAS TEF,GOIANIA,Comercio varejista de calcados,VAREJO,MODA,DISTRIBUICAO & VAREJO - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,...,GO,6.010675e+01,0.0-0.5M,181,1.0,60.106753,0,2,3,2
10612,TFEEYH,CONS SAT OU MFE BALANC SUBSC,SAAS SERIE T,ITAITINGA,"Comercio varejista de mercadorias em geral, co...",VAREJO,SUPERMERCADO,SUPERMERCADOS - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,...,CE,3.600225e+02,0.0-0.5M,181,1.0,360.022549,0,2,3,2
10613,TFEEYP,ALMOXARIFADO E ESTOQUE,SAAS CMNET HOTAL,CANELA,Hoteis,HOSPITALITY,HOSPEDAGEM,HOSPITALIDADE - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,...,RS,1.705934e+03,0.0-0.5M,181,1.0,1705.933728,0,2,3,2
10614,TFEEYQ,ADESAO TOTVS P,CLOUD COMPUTING.,SAOPAULO,Servicos advocaticios,JURIDICO,ESCRITORIO DE ADVOCACIA,CLOUD,MODALIDADE SERVICOS RECORRENTES,105,...,SP,5.656080e+03,0.0-0.5M,181,1.0,5656.079896,0,2,3,2

In [47]:
df_novo_cliente_1

,CD_CLIENTE,DS_PROD_MODA,DS_LIN_REC_MODA,CIDADE,DS_CNAE,DS_SEGMENTO,DS_SUBSEGMENTO,MARCA_TOTVS_MODA,MODAL_COMERC_MODA,PAIS,PERIODICIDADE_MODA,UF,VL_TOTAL_CONTRATO_SOMA,FAIXA_VLR_TOT_SOMA_CONTRATOS,DIAS_CLIENTE,QTD_CONTRATACOES_12M,VLR_CONTRATACOES_12M
2186,0,APLICATIVO MOBILE - STAFF,SAAS CMNET HOTAL,SAOPAULO,Apart-hoteis,HOSPITALITY,HOSPEDAGEM,HOSPITALIDADE - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,00 - Mensal,SP,401.569271,0.0-0.5M,2887,0.0,0.0

In [48]:
df.drop(columns=['CLUSTER_3', 'CLUSTER_4', 'CLUSTER_6'], inplace=True)

In [49]:
df_novo_cliente_1['CLUSTER_5'] = cluster_resultado

In [50]:
df_unido = pd.concat([df, df_novo_cliente_1], ignore_index=True)

In [51]:
df_unido.tail()

,CD_CLIENTE,DS_PROD_MODA,DS_LIN_REC_MODA,CIDADE,DS_CNAE,DS_SEGMENTO,DS_SUBSEGMENTO,MARCA_TOTVS_MODA,MODAL_COMERC_MODA,PAIS,PERIODICIDADE_MODA,UF,VL_TOTAL_CONTRATO_SOMA,FAIXA_VLR_TOT_SOMA_CONTRATOS,DIAS_CLIENTE,QTD_CONTRATACOES_12M,VLR_CONTRATACOES_12M,CLUSTER_5
10611,TFEEYC,TEF TOTVS CLOUD PDV PRINCIPAL,SAAS TEF,GOIANIA,Comercio varejista de calcados,VAREJO,MODA,DISTRIBUICAO & VAREJO - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,00 - Mensal,GO,60.106753,0.0-0.5M,181,1.0,60.106753,3
10612,TFEEYH,CONS SAT OU MFE BALANC SUBSC,SAAS SERIE T,ITAITINGA,"Comercio varejista de mercadorias em geral, co...",VAREJO,SUPERMERCADO,SUPERMERCADOS - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,00 - Mensal,CE,360.022549,0.0-0.5M,181,1.0,360.022549,3
10613,TFEEYP,ALMOXARIFADO E ESTOQUE,SAAS CMNET HOTAL,CANELA,Hoteis,HOSPITALITY,HOSPEDAGEM,HOSPITALIDADE - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,00 - Mensal,RS,1705.933728,0.0-0.5M,181,1.0,1705.933728,3
10614,TFEEYQ,ADESAO TOTVS P,CLOUD COMPUTING.,SAOPAULO,Servicos advocaticios,JURIDICO,ESCRITORIO DE ADVOCACIA,CLOUD,MODALIDADE SERVICOS RECORRENTES,105,00 - Mensal,SP,5656.079896,0.0-0.5M,181,1.0,5656.079896,3
10615,0,APLICATIVO MOBILE - STAFF,SAAS CMNET HOTAL,SAOPAULO,Apart-hoteis,HOSPITALITY,HOSPEDAGEM,HOSPITALIDADE - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,00 - Mensal,SP,401.569271,0.0-0.5M,2887,0.0,0.000000,3

In [52]:
df_unido = df_unido[df_unido['CLUSTER_5'] == cluster_resultado]

In [53]:
cluster_resultado

np.uint16(3)

In [54]:
# Cria a nova coluna preenchendo todas as linhas com 'N'.
df_unido['Cliente_Novo'] = 0

# --- 2. Atribuir o valor 'S' à última linha desta coluna ---

# Usa o .iloc[-1] para selecionar a última linha do DataFrame,
# e então o nome da coluna para acessar a célula específica.
# O '-1' no .iloc garante que a última posição seja sempre selecionada.
df_unido.iloc[-1, df_unido.columns.get_loc('Cliente_Novo')] = 1

# Alternativa mais compacta, mas dependente do Pandas 1.1+
# df.loc[df.index[-1], NOME_DA_NOVA_COLUNA] = 'S'

In [55]:
df_unido.tail()

,CD_CLIENTE,DS_PROD_MODA,DS_LIN_REC_MODA,CIDADE,DS_CNAE,DS_SEGMENTO,DS_SUBSEGMENTO,MARCA_TOTVS_MODA,MODAL_COMERC_MODA,PAIS,PERIODICIDADE_MODA,UF,VL_TOTAL_CONTRATO_SOMA,FAIXA_VLR_TOT_SOMA_CONTRATOS,DIAS_CLIENTE,QTD_CONTRATACOES_12M,VLR_CONTRATACOES_12M,CLUSTER_5,Cliente_Novo
10611,TFEEYC,TEF TOTVS CLOUD PDV PRINCIPAL,SAAS TEF,GOIANIA,Comercio varejista de calcados,VAREJO,MODA,DISTRIBUICAO & VAREJO - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,00 - Mensal,GO,60.106753,0.0-0.5M,181,1.0,60.106753,3,0
10612,TFEEYH,CONS SAT OU MFE BALANC SUBSC,SAAS SERIE T,ITAITINGA,"Comercio varejista de mercadorias em geral, co...",VAREJO,SUPERMERCADO,SUPERMERCADOS - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,00 - Mensal,CE,360.022549,0.0-0.5M,181,1.0,360.022549,3,0
10613,TFEEYP,ALMOXARIFADO E ESTOQUE,SAAS CMNET HOTAL,CANELA,Hoteis,HOSPITALITY,HOSPEDAGEM,HOSPITALIDADE - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,00 - Mensal,RS,1705.933728,0.0-0.5M,181,1.0,1705.933728,3,0
10614,TFEEYQ,ADESAO TOTVS P,CLOUD COMPUTING.,SAOPAULO,Servicos advocaticios,JURIDICO,ESCRITORIO DE ADVOCACIA,CLOUD,MODALIDADE SERVICOS RECORRENTES,105,00 - Mensal,SP,5656.079896,0.0-0.5M,181,1.0,5656.079896,3,0
10615,0,APLICATIVO MOBILE - STAFF,SAAS CMNET HOTAL,SAOPAULO,Apart-hoteis,HOSPITALITY,HOSPEDAGEM,HOSPITALIDADE - CORE,MODALIDADE ASSINATURA COMPLEMENTAR,105,00 - Mensal,SP,401.569271,0.0-0.5M,2887,0.0,0.000000,3,1

## PCA

In [56]:
# 1. Supondo que seu DataFrame se chama 'df_novo_cliente_1_clusterizado'
# 2. Defina qual é a coluna de cluster

# 3. Separe as features (X) e os clusters (y)
# Exclua a coluna de clusterização (e outras colunas irrelevantes como IDs) do conjunto X
X = df_unido.drop(columns=['ID_CLIENTE'], errors='ignore')
# Aplicando One-Hot Encoding em todas as colunas categóricas
X_encoded = pd.get_dummies(X)

from sklearn.preprocessing import StandardScaler

# 3.1 Escalonamento/Normalização das features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_encoded)

### 2D

In [57]:
from sklearn.decomposition import PCA

# 2.2 Configuração e aplicação do t-SNE (AGORA COM 2 COMPONENTES)
# - n_components=2: para visualização 2D
pca2 = PCA(n_components=2)
X_pca2 = pca2.fit_transform(X_scaled)

# 3.3 Atribuição direta (Se a ordem for garantida)
df_unido['pca_C1_2D'] = X_pca2[:, 0]  # Primeira coluna de X_pca2
df_unido['pca_C2_2D'] = X_pca2[:, 1]  # Segunda coluna de X_pca2

### 3D

In [58]:
# 2.2 Configuração e aplicação do t-SNE (AGORA COM 2 COMPONENTES)
# - n_components=2: para visualização 2D
pca3 = PCA(n_components=3)
X_pca3 = pca3.fit_transform(X_scaled)

# 3.3 Atribuição direta (Se a ordem for garantida)
df_unido['pca_C1_3D'] = X_pca3[:, 0]  # Primeira coluna de X_pca2
df_unido['pca_C2_3D'] = X_pca3[:, 1]  # Segunda coluna de X_pca2
df_unido['pca_C3_3D'] = X_pca3[:, 2]  # Segunda coluna de X_pca2

## Visualização 2D

In [59]:
import plotly.express as px

COLUNA_CLUSTER = 'CLUSTER_5'

# A coluna de cluster (COLUNA_CLUSTER) precisa ser do tipo string/object para o Plotly
# Se a sua coluna de cluster (ex: 'CLUSTER_5') for numérica (int/uint), converta-a:
df_unido[COLUNA_CLUSTER] = df_unido[COLUNA_CLUSTER].astype(str)

# --- Criação do Gráfico Interativo ---
fig = px.scatter(
    df_unido,
    x="pca_C1_2D",
    y="pca_C2_2D",
    # Define a coluna que será usada para colorir os pontos (os clusters)
    color='Cliente_Novo',
    # Você pode usar a paleta "hls" do Plotly, ou outras
    color_discrete_sequence=px.colors.qualitative.Alphabet,
    # Texto que aparece ao passar o mouse sobre os pontos
    hover_data=['Cliente_Novo'],
    title=f'Visualização Interativa de Clusters com t-SNE do Cluster {cluster_resultado}'
)

# --- Personalização e Layout ---
fig.update_layout(
    xaxis_title='Componente t-SNE 1',
    yaxis_title='Componente t-SNE 2',
    height=600,  # Altura da figura
    width=800    # Largura da figura
)

# Adiciona uma grade simples (opcional)
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey')
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey')

# Mostra o gráfico (será interativo no Jupyter Notebook/Colab)
fig.show()

## Visualização 3D

In [60]:
# Garante que o Plotly trate a coluna de cluster como categoria (string)
df_unido['Cliente_Novo'] = df_unido['Cliente_Novo'].astype(str)

# --- Criação do Gráfico 3D Interativo ---
fig = px.scatter_3d(
    df_unido,
    x="pca_C1_3D",
    y="pca_C2_3D",
    z="pca_C3_3D",  # O novo eixo Z
    # Define a coluna que será usada para colorir os pontos (os clusters)
    color='Cliente_Novo',
    # Você pode usar a paleta "hls" do Plotly, ou outras
    color_discrete_sequence=px.colors.qualitative.Alphabet,
    # Texto que aparece ao passar o mouse sobre os pontos
    hover_data=['Cliente_Novo'],
    title=f'Visualização 3D Interativa de Clusters com PCA do Cluster {cluster_resultado}'
)

# --- Ajuste do Tamanho dos Pontos ---
# O parâmetro 'size' dentro de 'marker' controla o diâmetro dos pontos em pixels.
# O valor padrão costuma ser 5 ou 6. Diminuir para 3 ou 4 torna os pontos menores e mais nítidos.
fig.update_traces(
    marker=dict(
        size=4,  # <-- Reduz o tamanho dos pontos
        opacity=0.8 # Mantém a opacidade (opcional)
    ),
    selector=dict(mode='markers') # Garante que apenas os marcadores sejam afetados
)

# --- Personalização do Layout 3D ---
fig.update_layout(
    scene=dict(
        xaxis_title='Componente PCA 1',
        yaxis_title='Componente PCA 2',
        zaxis_title='Componente PCA 3'
    ),
    height=700,
    width=900
)

# Mostra o gráfico interativo
fig.show()

# Comparação Numérica

In [61]:
df_novo_cliente_1.T

                                                            2186
CD_CLIENTE                                                     0
DS_PROD_MODA                           APLICATIVO MOBILE - STAFF
DS_LIN_REC_MODA                                 SAAS CMNET HOTAL
CIDADE                                                  SAOPAULO
DS_CNAE                                             Apart-hoteis
DS_SEGMENTO                                          HOSPITALITY
DS_SUBSEGMENTO                                        HOSPEDAGEM
MARCA_TOTVS_MODA                            HOSPITALIDADE - CORE
MODAL_COMERC_MODA             MODALIDADE ASSINATURA COMPLEMENTAR
PAIS                                                         105
PERIODICIDADE_MODA                                   00 - Mensal
UF                                                            SP
VL_TOTAL_CONTRATO_SOMA                                401.569271
FAIXA_VLR_TOT_SOMA_CONTRATOS                            0.0-0.5M
DIAS_CLIENTE                                                2887
QTD_CONTRATACOES_12M                                         0.0
VLR_CONTRATACOES_12M                                         0.0
CLUSTER_5                                                      3

In [62]:
cluster_resultado

np.uint16(3)

In [63]:
# Definindo função de agregação pela moda
def agg_moda(x):
    m = x.dropna().mode()
    if not m.empty:
        return m.iloc[0]
    return np.nan

In [64]:
# Definindo função de agregação pelo top 5 da moda
def top5_comuns(x):
    return x.dropna().value_counts().head(5).index.tolist()

In [65]:
# Agregando os dados por cluster 5, utilizando a média para as colunas numéricas e a moda para as colunas categóricas
df_agrupado = df.groupby('CLUSTER_5').agg(
    QTD_CLIENTES=('CD_CLIENTE', 'nunique'),
    DS_PROD_moda=('DS_PROD_MODA', agg_moda),
    DS_PROD_top5=('DS_PROD_MODA', top5_comuns),
    DS_LIN_REC_moda=('DS_LIN_REC_MODA', agg_moda),
    DS_LIN_REC_top5=('DS_LIN_REC_MODA', top5_comuns),
    CIDADE_moda=('CIDADE', agg_moda),
    CIDADE_top5=('CIDADE', top5_comuns),
    DS_CNAE_moda=('DS_CNAE', agg_moda),
    DS_CNAE_top5=('DS_CNAE', top5_comuns),
    DS_SEGMENTO_moda=('DS_SEGMENTO', agg_moda),
    DS_SEGMENTO_top5=('DS_SEGMENTO', top5_comuns),
    DS_SUBSEGMENTO_moda=('DS_SUBSEGMENTO', agg_moda),
    DS_SUBSEGMENTO_top5=('DS_SUBSEGMENTO', top5_comuns),
    MARCA_TOTVS_moda=('MARCA_TOTVS_MODA', agg_moda),
    MARCA_TOTVS_top5=('MARCA_TOTVS_MODA', top5_comuns),
    MODAL_COMERC_moda=('MODAL_COMERC_MODA', agg_moda),
    MODAL_COMERC_top5=('MODAL_COMERC_MODA', top5_comuns),
    PAIS_moda=('PAIS', agg_moda),
    PAIS_top5=('PAIS', top5_comuns),
    PERIODICIDADE_moda=('PERIODICIDADE_MODA', agg_moda),
    PERIODICIDADE_top5=('PERIODICIDADE_MODA', top5_comuns),
    UF_moda=('UF', agg_moda),
    UF_top5=('UF', top5_comuns),
    VL_TOTAL_CONTRATO_sum=('VL_TOTAL_CONTRATO_SOMA', 'sum'),
    VL_TOTAL_CONTRATO_median=('VL_TOTAL_CONTRATO_SOMA', 'median'),
    VL_TOTAL_CONTRATO_mean=('VL_TOTAL_CONTRATO_SOMA', 'mean'),
    VL_TOTAL_CONTRATO_min=('VL_TOTAL_CONTRATO_SOMA', 'min'),
    VL_TOTAL_CONTRATO_max=('VL_TOTAL_CONTRATO_SOMA', 'max'),
    FAIXA_VLR_TOT_SOMA_CONTRATOS_moda=('FAIXA_VLR_TOT_SOMA_CONTRATOS', agg_moda),
    FAIXA_VLR_TOT_SOMA_CONTRATOS_top5=('FAIXA_VLR_TOT_SOMA_CONTRATOS', top5_comuns),
    DIAS_CLIENTE_median=('DIAS_CLIENTE', 'median'),
    DIAS_CLIENTE_mean=('DIAS_CLIENTE', 'mean'),
    DIAS_CLIENTE_min=('DIAS_CLIENTE', 'min'),
    DIAS_CLIENTE_max=('DIAS_CLIENTE', 'max'),
    QTD_CONTRATACOES_12M_sum=('QTD_CONTRATACOES_12M', 'sum'),
    QTD_CONTRATACOES_12M_median=('QTD_CONTRATACOES_12M', 'median'),
    QTD_CONTRATACOES_12M_mean=('QTD_CONTRATACOES_12M', 'mean'),
    QTD_CONTRATACOES_12M_min=('QTD_CONTRATACOES_12M', 'min'),
    QTD_CONTRATACOES_12M_max=('QTD_CONTRATACOES_12M', 'max'),
    VLR_CONTRATACOES_12M_sum=('VLR_CONTRATACOES_12M', 'sum'),
    VLR_CONTRATACOES_12M_median=('VLR_CONTRATACOES_12M', 'median'),
    VLR_CONTRATACOES_12M_mean=('VLR_CONTRATACOES_12M', 'mean'),
    VLR_CONTRATACOES_12M_min=('VLR_CONTRATACOES_12M', 'min'),
    VLR_CONTRATACOES_12M_max=('VLR_CONTRATACOES_12M', 'max'),
).reset_index()

In [66]:
df_agrupado[df_agrupado['CLUSTER_5'] == cluster_resultado].T

                                                                                   3
CLUSTER_5                                                                          3
QTD_CLIENTES                                                                   10110
DS_PROD_moda                                                      AHGORA ESTRATEGICO
DS_PROD_top5                       [AHGORA ESTRATEGICO, SMS TOTVS TEC USER, CDU F...
DS_LIN_REC_moda                                                    CDU TOTVS SERIE T
DS_LIN_REC_top5                    [CDU TOTVS SERIE T, SAAS SERIE T, SMS TOTVS SE...
CIDADE_moda                                                                 SAOPAULO
CIDADE_top5                        [SAOPAULO, RIODEJANEIRO, BELOHORIZONTE, BRASIL...
DS_CNAE_moda                                                                  Hoteis
DS_CNAE_top5                       [Hoteis, Comercio varejista de mercadorias em ...
DS_SEGMENTO_moda                                                            SERVICOS
DS_SEGMENTO_top5                   [SERVICOS, VAREJO, MANUFATURA, DISTRIBUICAO, C...
DS_SUBSEGMENTO_moda                                                PROVEDOR SERVICOS
DS_SUBSEGMENTO_top5                [PROVEDOR SERVICOS, ATACADISTA E DISTRIBUIDOR,...
MARCA_TOTVS_moda                                                           RH - CORE
MARCA_TOTVS_top5                   [RH - CORE, DISTRIBUICAO & VAREJO - CORE, BACK...
MODAL_COMERC_moda                                             MODALIDADE TRADICIONAL
MODAL_COMERC_top5                  [MODALIDADE TRADICIONAL, MODALIDADE ASSINATURA...
PAIS_moda                                                                        105
PAIS_top5                                                   [105, 63, 158, 586, 845]
PERIODICIDADE_moda                                                       00 - Mensal
PERIODICIDADE_top5                 [00 - Mensal, 11 - Anual, 02 - Trimestral, 05 ...
UF_moda                                                                           SP
UF_top5                                                         [SP, MG, SC, RJ, PR]
VL_TOTAL_CONTRATO_sum                                               232385841.646463
VL_TOTAL_CONTRATO_median                                                 4356.247198
VL_TOTAL_CONTRATO_mean                                                  22985.741013
VL_TOTAL_CONTRATO_min                                                       0.004204
VL_TOTAL_CONTRATO_max                                                  218750.286697
FAIXA_VLR_TOT_SOMA_CONTRATOS_moda                                           0.0-0.5M
FAIXA_VLR_TOT_SOMA_CONTRATOS_top5                                         [0.0-0.5M]
DIAS_CLIENTE_median                                                           2378.0
DIAS_CLIENTE_mean                                                        3077.473788
DIAS_CLIENTE_min                                                                 181
DIAS_CLIENTE_max                                                               13683
QTD_CONTRATACOES_12M_sum                                                      6755.0
QTD_CONTRATACOES_12M_median                                                      0.0
QTD_CONTRATACOES_12M_mean                                                    0.66815
QTD_CONTRATACOES_12M_min                                                         0.0
QTD_CONTRATACOES_12M_max                                                        60.0
VLR_CONTRATACOES_12M_sum                                             27047498.524688
VLR_CONTRATACOES_12M_median                                                      0.0
VLR_CONTRATACOES_12M_mean                                                2675.321318
VLR_CONTRATACOES_12M_min                                                         0.0
VLR_CONTRATACOES_12M_max                                               155916.092409